apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-management-deployment
  namespace: NAMESPACE_VAR
  labels:
    app: ProductManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ProductManagement
  template:
    metadata:
      labels:
        app: ProductManagement
    spec:
      containers:
      - name: productmanagement
        image: xom-ecomm-acr02-registry.cn-shanghai.cr.aliyuncs.com/tootest/bcs-product:GITHUB_SHA
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"

      imagePullSecrets:
        - name: alibaba-registry-credential-product
