apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE_VAR
  name: product-management-service
spec:
  selector:
    app: ProductManagement
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80